### ISSUE TITLE
Graphical corruption when returning to pokedex

### ISSUE THREAD

**Issue by clbr** [LeonarthCG/POKEPICROSS_Translation#1]
Thanks for making this translation, I had no idea the game even existed before stumbling upon your entry on rh.net. Having a blast so far.

v1.1 on a GBA SP on an Everdrive.

There's a minor issue when you return to the pokedex, the pokemon picture gets corrupted with some text pieces. It's just cosmetic, getting out of the menu works and nothing breaks.

Two ways to repro:
- try to print the entry without having a printer
- from the pokedex, press retry, and fail the match

**Comment by LeonarthCG** [comment]
Thanks for letting me know. I did confirm that this happens when failing to print, however, I haven't been able to replicate this at all with the second method. I would like to do that before I start working on a fix, is there anything else you did before failing the retry caused issues?

**Comment by clbr** [comment]
Sorry, I don't remember.
